"""empty message

Revision ID: 21ef4005d6bc
Revises: e8cf6a6bdb49
Create Date: 2022-02-24 23:29:24.727659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ef4005d6bc'
down_revision = 'e8cf6a6bdb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('show_on_profile', sa.Boolean(), nullable=True))
    op.alter_column('mdgPrototype-users', 'profile_picture',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'mdgPrototype-users', ['walletId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mdgPrototype-users', type_='unique')
    op.alter_column('mdgPrototype-users', 'profile_picture',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('asset', 'show_on_profile')
    # ### end Alembic commands ###
